//! Build script: embed the bundled mise "nix" backend plugin (the `mise/` tree)
//! into the binary. A hermetic sandbox has no host copy of the plugin to point
//! mise at, so the tree is carried inside the binary and materialized at launch.
//!
//! Walks `mise/` and generates a `(relative path, bytes)` table that the
//! `sandbox::miseplugin` module includes. Re-runs whenever any plugin file
//! changes, so the embedded copy never drifts from the source tree.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let plugin_root = manifest.join("mise");
    println!("cargo:rerun-if-changed={}", plugin_root.display());

    let mut files: Vec<(String, PathBuf)> = Vec::new();
    collect(&plugin_root, &plugin_root, &mut files);
    // Deterministic order, so the generated table (and any hash of it) is stable.
    files.sort();

    let mut out = String::from(
        "// @generated by build.rs — the embedded mise \"nix\" backend plugin tree.\n\
         /// Each entry is (path relative to the plugin root, file bytes).\n\
         pub(crate) static PLUGIN_FILES: &[(&str, &[u8])] = &[\n",
    );
    for (rel, abs) in &files {
        println!("cargo:rerun-if-changed={}", abs.display());
        out.push_str(&format!(
            "    ({:?}, include_bytes!({:?})),\n",
            rel,
            abs.to_str().expect("plugin path is valid UTF-8"),
        ));
    }
    out.push_str("];\n");

    let dest = PathBuf::from(env::var("OUT_DIR").unwrap()).join("mise_plugin_files.rs");
    fs::write(&dest, out).unwrap();
}

/// Collect every file under `dir` as `(path relative to `root`, absolute path)`,
/// recursing into subdirectories. The relative path is forward-slashed, which is
/// what an in-sandbox path needs.
fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    for entry in fs::read_dir(dir).unwrap() {
        let path = entry.unwrap().path();
        if path.is_dir() {
            collect(root, &path, out);
        } else {
            let rel = path
                .strip_prefix(root)
                .unwrap()
                .to_str()
                .expect("plugin path is valid UTF-8")
                .to_string();
            out.push((rel, path));
        }
    }
}
