//! Build script: embed two source trees into the binary.
//!
//! 1. The bundled mise "nix" backend plugin (`mise/`). A hermetic sandbox has no host copy
//!    of the plugin to point mise at, so the tree is carried inside the binary and
//!    materialized at launch.
//! 2. The default resolver-plugin store (`plugins/`). The built-in resolvers ship inside the
//!    binary so `ops plugins install <name>` can place one with no fetch, network, or
//!    signature — trust is the binary itself.
//!
//! Each tree is walked into a `(path, bytes)` table that a module includes. Both re-run
//! whenever a source file changes, so the embedded copies never drift.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    emit_mise_plugin(&manifest, &out_dir);
    emit_default_store(&manifest, &out_dir);
}

/// Embed the `mise/` tree as a flat `(relative path, bytes)` table the `sandbox::miseplugin`
/// module includes.
fn emit_mise_plugin(manifest: &Path, out_dir: &Path) {
    let plugin_root = manifest.join("mise");
    println!("cargo:rerun-if-changed={}", plugin_root.display());

    let mut files: Vec<(String, PathBuf)> = Vec::new();
    collect(&plugin_root, &plugin_root, &mut files);
    // Deterministic order, so the generated table (and any hash of it) is stable.
    files.sort();

    let mut out = String::from(
        "// @generated by build.rs — the embedded mise \"nix\" backend plugin tree.\n\
         /// Each entry is (path relative to the plugin root, file bytes).\n\
         pub(crate) static PLUGIN_FILES: &[(&str, &[u8])] = &[\n",
    );
    for (rel, abs) in &files {
        println!("cargo:rerun-if-changed={}", abs.display());
        out.push_str(&format!(
            "    ({:?}, include_bytes!({:?})),\n",
            rel,
            abs.to_str().expect("plugin path is valid UTF-8"),
        ));
    }
    out.push_str("];\n");

    fs::write(out_dir.join("mise_plugin_files.rs"), out).unwrap();
}

/// Embed the `plugins/` tree as a `(plugin name, relative path, bytes)` table the `plugins`
/// module includes. Each top-level subdirectory of `plugins/` is one plugin; a file directly
/// under `plugins/` (such as `README.md`) is documentation and is not embedded.
fn emit_default_store(manifest: &Path, out_dir: &Path) {
    let store_root = manifest.join("plugins");
    println!("cargo:rerun-if-changed={}", store_root.display());

    let mut files: Vec<(String, PathBuf)> = Vec::new();
    collect(&store_root, &store_root, &mut files);
    files.sort();

    let mut out = String::from(
        "// @generated by build.rs — the embedded default resolver-plugin store.\n\
         /// Each entry is (plugin directory name, path relative to that directory, file bytes).\n\
         pub(crate) static STORE_FILES: &[(&str, &str, &[u8])] = &[\n",
    );
    for (rel, abs) in &files {
        // Only a file inside a plugin subdirectory belongs to the store; a top-level file has
        // no `/` once made relative and is skipped.
        let Some((plugin, subpath)) = rel.split_once('/') else {
            continue;
        };
        println!("cargo:rerun-if-changed={}", abs.display());
        out.push_str(&format!(
            "    ({:?}, {:?}, include_bytes!({:?})),\n",
            plugin,
            subpath,
            abs.to_str().expect("plugin path is valid UTF-8"),
        ));
    }
    out.push_str("];\n");

    fs::write(out_dir.join("store_plugin_files.rs"), out).unwrap();
}

/// Collect every file under `dir` as `(path relative to `root`, absolute path)`, recursing into
/// subdirectories. The relative path is forward-slashed, which is what an in-sandbox path needs.
fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    for entry in fs::read_dir(dir).unwrap() {
        let path = entry.unwrap().path();
        if path.is_dir() {
            collect(root, &path, out);
        } else {
            let rel = path
                .strip_prefix(root)
                .unwrap()
                .to_str()
                .expect("plugin path is valid UTF-8")
                .to_string();
            out.push((rel, path));
        }
    }
}
