//! Build script: embed source trees, and (optionally) a static nix engine, into the binary.
//!
//! 1. The bundled mise "nix" backend plugin (`mise/`). A hermetic sandbox has no host copy
//!    of the plugin to point mise at, so the tree is carried inside the binary and
//!    materialized at launch.
//! 2. The default resolver-plugin store (`plugins/`). The built-in resolvers ship inside the
//!    binary so `ops plugins install <name>` can place one with no fetch, network, or
//!    signature — trust is the binary itself.
//! 3. With the `bundled-nix` feature, a statically-linked `nix` binary, so the shipped ops
//!    drives its own store with no host nix. The binary is supplied out-of-band via the
//!    `OPS_BUNDLED_NIX` env var (produced by `mise run build-bundled`), keeping this script
//!    free of any fetch mechanism, and is verified against a pinned hash so a drift fails
//!    here, loudly, rather than at a user's first launch.
//!
//! Each tree is walked into a `(path, bytes)` table that a module includes. Both re-run
//! whenever a source file changes, so the embedded copies never drift.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

/// The static nix engine ops embeds under the `bundled-nix` feature, pinned for
/// reproducibility. Produced by `mise run build-bundled` from
/// `github:NixOS/nixpkgs/89570f24e97e614aa34aa9ab1c927b6578a43775#pkgsStatic.nix`
/// (nix 2.34.7, x86_64 static musl). `EXPECTED_NIX_SHA256` is the SHA-256 of that
/// binary's bytes; the build fails if the supplied engine does not match it.
const EXPECTED_NIX_SHA256: &str =
    "8ebec57b2f50bd10e62ac2e4ae27058a22019f8840ae278e2da9a7efe16faf80";

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    emit_mise_plugin(&manifest, &out_dir);
    emit_default_store(&manifest, &out_dir);
    emit_bundled_nix(&out_dir);
}

/// Embed the static nix engine when the `bundled-nix` feature is on, writing the module
/// `store::bundled` includes (`NIX_BIN` bytes + their `NIX_SHA256`). The engine is read
/// from the path in `OPS_BUNDLED_NIX` and verified against [`EXPECTED_NIX_SHA256`]. With
/// the feature off (the default), this is a no-op: ops resolves nix from `OPS_NIX_BIN`/`PATH`.
fn emit_bundled_nix(out_dir: &Path) {
    // Re-run if the supplying var changes, so a re-point re-embeds.
    println!("cargo:rerun-if-env-changed=OPS_BUNDLED_NIX");
    if env::var_os("CARGO_FEATURE_BUNDLED_NIX").is_none() {
        return;
    }
    let src = env::var_os("OPS_BUNDLED_NIX").unwrap_or_else(|| {
        panic!(
            "the `bundled-nix` feature is enabled but OPS_BUNDLED_NIX is unset — point it \
             at a static `nix` binary (use `mise run build-bundled`, which produces one)"
        )
    });
    let src = PathBuf::from(src);
    println!("cargo:rerun-if-changed={}", src.display());
    let bytes = fs::read(&src)
        .unwrap_or_else(|e| panic!("reading OPS_BUNDLED_NIX ({}): {e}", src.display()));
    let got = sha256_hex(&bytes);
    assert_eq!(
        got,
        EXPECTED_NIX_SHA256,
        "bundled nix sha256 mismatch — OPS_BUNDLED_NIX ({}) is not the pinned engine \
         (got {got}, expected {EXPECTED_NIX_SHA256}); rebuild it from the pinned nixpkgs \
         ref or bump the pin in build.rs",
        src.display(),
    );
    let bin = out_dir.join("bundled_nix.bin");
    fs::write(&bin, &bytes).unwrap();
    let generated = format!(
        "// @generated by build.rs — the embedded static nix engine.\n\
         pub static NIX_BIN: &[u8] = include_bytes!({:?});\n\
         pub const NIX_SHA256: &str = {EXPECTED_NIX_SHA256:?};\n",
        bin.to_str().expect("OUT_DIR path is valid UTF-8"),
    );
    fs::write(out_dir.join("bundled_nix.rs"), generated).unwrap();
}

/// Hex SHA-256 of `bytes`, for the build-time integrity check on the embedded engine.
fn sha256_hex(bytes: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    Sha256::digest(bytes)
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect()
}

/// Embed the `mise/` tree as a flat `(relative path, bytes)` table the `sandbox::miseplugin`
/// module includes.
fn emit_mise_plugin(manifest: &Path, out_dir: &Path) {
    let plugin_root = manifest.join("mise");
    println!("cargo:rerun-if-changed={}", plugin_root.display());

    let mut files: Vec<(String, PathBuf)> = Vec::new();
    collect(&plugin_root, &plugin_root, &mut files);
    // Deterministic order, so the generated table (and any hash of it) is stable.
    files.sort();

    let mut out = String::from(
        "// @generated by build.rs — the embedded mise \"nix\" backend plugin tree.\n\
         /// Each entry is (path relative to the plugin root, file bytes).\n\
         pub(crate) static PLUGIN_FILES: &[(&str, &[u8])] = &[\n",
    );
    for (rel, abs) in &files {
        println!("cargo:rerun-if-changed={}", abs.display());
        out.push_str(&format!(
            "    ({:?}, include_bytes!({:?})),\n",
            rel,
            abs.to_str().expect("plugin path is valid UTF-8"),
        ));
    }
    out.push_str("];\n");

    fs::write(out_dir.join("mise_plugin_files.rs"), out).unwrap();
}

/// Embed the `plugins/` tree as a `(plugin name, relative path, bytes)` table the `plugins`
/// module includes. Each top-level subdirectory of `plugins/` is one plugin; a file directly
/// under `plugins/` (such as `README.md`) is documentation and is not embedded.
fn emit_default_store(manifest: &Path, out_dir: &Path) {
    let store_root = manifest.join("plugins");
    println!("cargo:rerun-if-changed={}", store_root.display());

    let mut files: Vec<(String, PathBuf)> = Vec::new();
    collect(&store_root, &store_root, &mut files);
    files.sort();

    let mut out = String::from(
        "// @generated by build.rs — the embedded default resolver-plugin store.\n\
         /// Each entry is (plugin directory name, path relative to that directory, file bytes).\n\
         pub(crate) static STORE_FILES: &[(&str, &str, &[u8])] = &[\n",
    );
    for (rel, abs) in &files {
        // Only a file inside a plugin subdirectory belongs to the store; a top-level file has
        // no `/` once made relative and is skipped.
        let Some((plugin, subpath)) = rel.split_once('/') else {
            continue;
        };
        println!("cargo:rerun-if-changed={}", abs.display());
        out.push_str(&format!(
            "    ({:?}, {:?}, include_bytes!({:?})),\n",
            plugin,
            subpath,
            abs.to_str().expect("plugin path is valid UTF-8"),
        ));
    }
    out.push_str("];\n");

    fs::write(out_dir.join("store_plugin_files.rs"), out).unwrap();
}

/// Collect every file under `dir` as `(path relative to `root`, absolute path)`, recursing into
/// subdirectories. The relative path is forward-slashed, which is what an in-sandbox path needs.
fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    for entry in fs::read_dir(dir).unwrap() {
        let path = entry.unwrap().path();
        if path.is_dir() {
            collect(root, &path, out);
        } else {
            let rel = path
                .strip_prefix(root)
                .unwrap()
                .to_str()
                .expect("plugin path is valid UTF-8")
                .to_string();
            out.push((rel, path));
        }
    }
}
