import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Replaces the hand-maintained `nav:` list from the old mkdocs.yml. Docusaurus
// walks the guide/ tree and builds the section order from frontmatter `sidebar_position`,
// so new pages join automatically instead of requiring a nav edit.
const sidebars: SidebarsConfig = {
  guideSidebar: [
    'index',
    {
      type: 'category',
      label: 'Getting started',
      items: ['getting-started/installation', 'getting-started/quickstart', 'getting-started/doctor'],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        'concepts/overview',
        'concepts/security-model',
        'concepts/trust',
        'concepts/enforcement',
        'concepts/observability',
        'concepts/provisioning',
        'concepts/directory-layout',
      ],
    },
    {
      type: 'category',
      label: 'Configuration',
      items: [
        'configuration/index',
        'configuration/env',
        'configuration/binds',
        'configuration/packages',
        'configuration/tools',
        'configuration/nixpkgs',
        'configuration/limits',
        'configuration/seccomp',
        'configuration/devices',
        'configuration/ssh-agent',
        'configuration/gui',
        'configuration/gpu',
        'configuration/audio',
        'configuration/dbus',
        'configuration/network',
        'configuration/proc',
        'configuration/notify',
        'configuration/secret',
        'configuration/task',
        'configuration/apps',
        'configuration/net-groups',
        'configuration/bundles',
        'configuration/overrides',
      ],
    },
    {
      type: 'category',
      label: 'Command reference',
      items: [
        'cli/index',
        'cli/doctor',
        'cli/run',
        'cli/app',
        'cli/mise',
        'cli/search',
        'cli/test',
        'cli/bundle',
        'cli/net',
        'cli/proc',
        'cli/fs',
        'cli/ssh-agent',
        'cli/task',
        'cli/secret',
        'cli/plugins',
        'cli/projects',
        'cli/session',
        'cli/trust',
        'cli/untrust',
        'cli/config',
        'cli/upgrade',
        'cli/gc',
        'cli/storage',
        'cli/store',
        'cli/path',
      ],
    },
    {
      type: 'category',
      label: 'Apps and profiles',
      items: ['apps/index', 'apps/home', 'apps/profiles', 'apps/catalog'],
    },
    {
      type: 'category',
      label: 'Networking',
      items: [
        'networking/index',
        'networking/architecture',
        'networking/modes',
        'networking/rules',
        'networking/groups',
        'networking/forward',
        'networking/ask',
        'networking/observability',
      ],
    },
    {
      type: 'category',
      label: 'Secrets',
      items: [
        'secrets/index',
        'secrets/resolvers',
        'secrets/injection',
        'secrets/redaction',
        'secrets/plugins',
      ],
    },
    {
      type: 'category',
      label: 'Housekeeping',
      items: ['housekeeping/sessions', 'housekeeping/gc', 'housekeeping/upgrade'],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [
        'reference/environment-variables',
        'reference/exit-codes',
        'reference/glossary',
      ],
    },
  ],
};

export default sidebars;
